title: Pteralix | DevOps for Real
author:
  name: Cads Oakley
metadata:
    description: 'DevOps for startups, enterprises and the rest of us'

# Header customization
header:
  title: Cædman Oakley
  description: I roll my sleeves up and get things done. I’m a <span>collaboration conjurer</span>, a facilitator and an unblocker, <span>removing obstacles</span> and helping people do their best work.  As a <span>DevOps devotee</span>, I speak at conferences and meetups and promote the DevOps mentality.  There is, however, much more to learn <a class="smoothscroll" href="#about">about me</a>.
copyright:
    - line: &copy; Copyright 2014 CeeVee
    - line: Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>
social:
- url: "https://twitter.com/cadsoakley"
  icon: twitter
- url: "https://github.com/yokai"
  icon: github
- url: "https://linkedin.com/in/cadsoakley"
  icon: linkedin


# HOW TO CREATE A VALID ID TO USE:
# Go to www.twitter.com and sign in as normal, go to your settings page.
# Go to "Widgets" on the left hand side.
# Create a new widget for what you need eg "user time line" or "search" etc.
# Feel free to check "exclude replies" if you don't want replies in results.
# Now go back to settings page, and then go back to widgets page and
# you should see the widget you just created. Click edit.
# Look at the URL in your web browser, you will see a long number like this:
# 657554810648948736
# Use this as your ID below instead!

twitter:
  id: '662737203018100736' # Your widget ID
  domId: 'tw-widget1' # HTML ID used in code
  maxTweets: 3 # How many tweets to display
  enableLinks: 'true' # Enable links
  showInteraction: 'false' # Show interaction
  showImages: 'false'  # Show images
  showUser: 'false' # Show user name
